/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JSONCreator.Constantes;
import JSONCreator.JSONCreator;
import Network.NetworkManager;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.charset.StandardCharsets;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Steven
 */
public class CargaLibros extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargaLibros
     */
    private CentralGUI Centralgui;
    private NetworkManager NetManager;
    public CargaLibros(CentralGUI Celtralgui) {
        this.Centralgui = Celtralgui;
        this.NetManager = Centralgui.getLibraryManager().getNetworkManager();
        setName(Constantes.GUI_VENTANA_CARGA_LIBROS);
        initComponents();
        FileNameExtensionFilter jsonfilter = new FileNameExtensionFilter("JSON File", "json");
        CargaMasivaLibros.setFileFilter(jsonfilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargaMasivaLibros = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Carga Masiva - Libros");
        setVisible(true);

        CargaMasivaLibros.setApproveButtonText("Abrir");
        CargaMasivaLibros.setApproveButtonToolTipText("");
        CargaMasivaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaMasivaLibrosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carga Masiva de Libros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CargaMasivaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CargaMasivaLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaMasivaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaMasivaLibrosActionPerformed
        switch (evt.getActionCommand()) {
            case "ApproveSelection":
            System.out.println("Cargando usuarios");
            FileReader fileReader;
            JSONParser jsonParser = new JSONParser();
            
                FileReader reader;
            try {
                reader = new FileReader(CargaMasivaLibros.getSelectedFile().getAbsolutePath(), StandardCharsets.UTF_8);
                JSONParser jparser = new JSONParser();
                JSONObject Data = (JSONObject) jparser.parse(reader);
                JSONCreator.parseCargaLibros(Data,NetManager,Centralgui.getLibraryManager().getLibrero(), Centralgui.getLibraryManager().getLibreroGlobal(),this);
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(CargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(CargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(CargaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            this.hide();
            System.out.println("Termine carga masiva");
            break;
        }
    }//GEN-LAST:event_CargaMasivaLibrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser CargaMasivaLibros;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
