/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JSONCreator.Constantes;
import biblioteca.Biblioteca;
import biblioteca.Categoria;
import biblioteca.Estructuras.NodoAVL;
import javax.swing.JOptionPane;

/**
 *
 * @author Steven
 */
public class CrearCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearCategoria
     */
    private CentralGUI Centralgui;
    private Biblioteca LibraryManager;
    public CrearCategoria(CentralGUI Centralgui) {
        this.Centralgui = Centralgui;
        this.LibraryManager = Centralgui.getLibraryManager();
        super.setName(Constantes.GUI_VENTANA_CREAR_CATEGORIA);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Categoria = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear Categoria");
        setVisible(true);

        jLabel1.setText("Nombre :");

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        if(Categoria.getText().matches("[ ]+")){
            JOptionPane.showMessageDialog(this,"Nombre de categoria invalido.");
        }else{
            Categoria nueva = new Categoria(Categoria.getText(), LibraryManager.getNetworkManager().getLoggedUser().getCarnet());
            NodoAVL retorno = LibraryManager.getLibrero().InsertNew(nueva, false);
            if(retorno == null){
                JOptionPane.showMessageDialog(this, "Esa categoria ya existe.");
            }else{
                JOptionPane.showMessageDialog(this, "Categoria creada correctamente.");
                Centralgui.getLibraryManager().getBlockChain().setPendingChange(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_CrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Categoria;
    private javax.swing.JButton Crear;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
