/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.Libro;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Steven
 */
public class FilaLibro extends javax.swing.JPanel {

    /**
     * Creates new form FilaLibro
     */
    private CentralGUI Centralgui;
    private Libro Libro;
    private String Nombre;
    private JPanel Resultados;

    public FilaLibro(CentralGUI Centralgui, Libro Libro, JPanel Resultados) {
        this.Centralgui = Centralgui;
        this.Resultados = Resultados;
        this.Libro = Libro;
        this.Nombre = Libro.getISBN() + "";
        initComponents();
        this.LibroTitle.setText(Libro.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibroTitle = new javax.swing.JLabel();
        Reporte = new javax.swing.JButton();

        LibroTitle.setText("Hola como estas jaja");

        Reporte.setText("Ver Detalles");
        Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibroTitle)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Reporte)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LibroTitle)
                    .addComponent(Reporte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteActionPerformed
        JInternalFrame ventana = Centralgui.existWindow(Centralgui.getDesktop(), Nombre);

        if (ventana == null) {
            ventana = new verLibro(Centralgui,Libro, Resultados, this);
            Centralgui.getDesktop().add(ventana);
            Centralgui.getDesktop().getDesktopManager().activateFrame(ventana);
        } else {
            try {
                ventana.setIcon(false);
                ventana.show();
                Centralgui.getDesktop().getDesktopManager().activateFrame(ventana);
            } catch (PropertyVetoException ex) {
                java.util.logging.Logger.getLogger(FilaLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibroTitle;
    private javax.swing.JButton Reporte;
    // End of variables declaration//GEN-END:variables
}
