/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import JSONCreator.Constantes;
import JSONCreator.JSONCreator;
import java.beans.PropertyVetoException;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Steven
 */
public class Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuarios
     */
    private CentralGUI Centralgui;

    public Usuarios(CentralGUI Centralgui) {
        setName(Constantes.GUI_VENTANA_CARGA_USUARIOS);
        this.Centralgui = Centralgui;
        initComponents();
        FileNameExtensionFilter jsonfilter = new FileNameExtensionFilter("JSON File", "json");
        CargaMasivaUsuarios.setFileFilter(jsonfilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        CargaMasivaUsuarios = new javax.swing.JFileChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Carga Masiva - Usuarios");
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carga Masiva de Usuarios");

        CargaMasivaUsuarios.setApproveButtonText("Abrir");
        CargaMasivaUsuarios.setApproveButtonToolTipText("");
        CargaMasivaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaMasivaUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CargaMasivaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CargaMasivaUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaMasivaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaMasivaUsuariosActionPerformed
        switch (evt.getActionCommand()) {
            case "ApproveSelection":
                System.out.println("Cargando usuarios");
                FileReader fileReader;
                JSONParser jsonParser = new JSONParser();
                try {
                    FileReader reader = new FileReader(CargaMasivaUsuarios.getSelectedFile().getAbsolutePath());
                    JSONParser jparser = new JSONParser();
                    JSONObject Data = (JSONObject) jparser.parse(reader);
                    JSONCreator.parseDataBlock(
                            Data.toJSONString(),
                            Centralgui.getVirtualLibrary().getNetworkManager(),
                            Centralgui.getVirtualLibrary().getLibrero(),
                            Centralgui.getVirtualLibrary().getUsuarios(),
                            false, this);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.hide();
                System.out.println("Termine carga masiva");
                break;
        }
    }//GEN-LAST:event_CargaMasivaUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser CargaMasivaUsuarios;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
