/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import biblioteca.Categoria;
import biblioteca.Libro;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Steven
 */
public class verLibro extends javax.swing.JInternalFrame {

    /**
     * Creates new form verLibro
     */
    private Libro Libro;
    private CentralGUI Centralgui;
    private boolean ActivateDelete = false;
    private JPanel Padre;
    private FilaLibro Origen;

    public verLibro(CentralGUI Centralgui, Libro Libro, JPanel Padre, FilaLibro Origen) {
        this.Centralgui = Centralgui;
        this.Libro = Libro;
        this.Padre = Padre;
        this.Origen = Origen;
        setTitle("Informacion de: " + Libro.getTitle());
        setName(Libro.getISBN() + "");
        initComponents();
        this.ISBN.setEditable(false);
        this.Categoria.setEditable(false);
        ContenedorRazon.setVisible(false);
        if (this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser() != null) {
            if (this.Libro.getIDAuthor() != this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser().getCarnet()) {
                Guardar.setEnabled(false);
                Eliminar.setEnabled(false);
                ContenedorRazon.setVisible(false);
            }
        } else {
            Guardar.setEnabled(false);
            Eliminar.setEnabled(false);
            ContenedorRazon.setVisible(false);
        }
        placeValues();
    }

    private void placeValues() {
        this.Ano.setText(this.Libro.getYear() + "");
        this.Autor.setText(this.Libro.getAuthor());
        this.Carnet.setText(this.Libro.getIDAuthor() + "");
        this.Categoria.setText(this.Libro.getCategory());
        this.Edicion.setText(this.Libro.getEdition() + "");
        this.Editorial.setText(this.Libro.getPrinter());
        this.ISBN.setText(this.Libro.getISBN() + "");
        this.Idioma.setText(this.Libro.getLanguage());
        this.Titulo.setText(this.Libro.getTitle());
        if (this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser() != null) {
            if (this.Libro.getIDAuthor() != this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser().getCarnet()) {
                this.Ano.setEditable(false);
                this.Autor.setEditable(false);
                this.Carnet.setEditable(false);
                this.Categoria.setEditable(false);
                this.Edicion.setEditable(false);
                this.Editorial.setEditable(false);
                this.ISBN.setEditable(false);
                this.Idioma.setEditable(false);
                this.Titulo.setEditable(false);
            }
        } else {
            this.Ano.setEditable(false);
            this.Autor.setEditable(false);
            this.Carnet.setEditable(false);
            this.Categoria.setEditable(false);
            this.Edicion.setEditable(false);
            this.Editorial.setEditable(false);
            this.ISBN.setEditable(false);
            this.Idioma.setEditable(false);
            this.Titulo.setEditable(false);
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Categoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Edicion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Editorial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Autor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Carnet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Idioma = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ContenedorRazon = new javax.swing.JScrollPane();
        RazonEliminar = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setVisible(true);

        jLabel2.setText("ISBN: ");

        jLabel3.setText("Titulo:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Editorial:");

        jLabel6.setText("Año:");

        jLabel7.setText("Edicion: ");

        jLabel8.setText("Categoria:");

        jLabel9.setText("Idioma:");

        jLabel10.setText("Carnet (Publicador):");

        Carnet.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Informacion del libro");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        ContenedorRazon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRazon.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ContenedorRazon.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ContenedorRazon.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N

        RazonEliminar.setColumns(20);
        RazonEliminar.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        RazonEliminar.setRows(5);
        RazonEliminar.setText("Escribe una Justificacion para eliminar este libro...");
        ContenedorRazon.setViewportView(RazonEliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Carnet)
                                    .addComponent(Idioma, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(Categoria)
                                    .addComponent(Edicion)
                                    .addComponent(Ano)
                                    .addComponent(Editorial)
                                    .addComponent(Autor)
                                    .addComponent(Titulo)
                                    .addComponent(ISBN))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContenedorRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Eliminar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Eliminar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser() != null) {
            if (this.Libro.getIDAuthor() != this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser().getCarnet()) {
                String Mensaje = "";
                if (this.Titulo.getText() == "" || this.Titulo.getText().matches("[\\s]+")) {
                    Mensaje = Mensaje = "Titulo vacio o invalido.\n";
                }

                if (this.Autor.getText() == "" || this.Autor.getText().matches("[\\s]+")) {
                    Mensaje = Mensaje = "Autor vacio o invalido.\n";
                }

                if (this.Editorial.getText() == "" || this.Editorial.getText().matches("[\\s]+")) {
                    Mensaje = Mensaje = "Editorial vacia o invalida.\n";
                }

                if (!this.Ano.getText().matches("[0-9]+")) {
                    Mensaje = Mensaje = "Año vacio o invalido.\n";
                }

                if (!this.Edicion.getText().matches("[0-9]+")) {
                    Mensaje = Mensaje = "Edicion vacia o invalida.\n";
                }

                if (this.Idioma.getText() == "" || this.Idioma.getText().matches("[\\s]+")) {
                    Mensaje = Mensaje = "Idioma vacio o invalido.\n";
                }

                if (Mensaje == "") {
                    JOptionPane.showMessageDialog(this, Mensaje);
                } else {
                    this.Libro.setAuthor(this.Autor.getText());
                    this.Libro.setEdition(Integer.parseInt(this.Edicion.getText()));
                    this.Libro.setLanguage(this.Idioma.getText());
                    this.Libro.setPrinter(this.Editorial.getText());
                    this.Libro.setTitle(this.Titulo.getText());
                    this.Libro.setYear(Integer.parseInt(this.Ano.getText()));
                    JOptionPane.showMessageDialog(this, "Actualizado");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Este libro no te pertenece");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes iniciar sesion.");
        }

    }//GEN-LAST:event_GuardarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser() != null) {
            if (this.Libro.getIDAuthor() != this.Centralgui.getLibraryManager().getNetworkManager().getLoggedUser().getCarnet()) {
                if (!ActivateDelete) {
                    ActivateDelete = true;
                    ContenedorRazon.setVisible(true);
                    pack();
                } else {
                    if (RazonEliminar.getText() == "" || this.RazonEliminar.getText().matches("[\\s]+")) {
                        JOptionPane.showMessageDialog(this, "Debes escribir una razon valida para eliminanr el libro.");
                    } else {
                        String Categoria = this.Libro.getCategory();
                        Centralgui.getLibraryManager().getLibrero().BuscarCategoria(Categoria).getData().getLibrero().RemoveBook(this.Libro.getISBN(), false);
                        Centralgui.getLibraryManager().getLibreroGlobal().RemoveBook(this.Libro.getISBN(), true);
                        Padre.remove(Origen);
                        JOptionPane.showMessageDialog(this, "Libro Eliminado Correctamente.");
                        dispose();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Este libro no te pertenece");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes iniciar sesion.");
        }

    }//GEN-LAST:event_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ano;
    private javax.swing.JTextField Autor;
    private javax.swing.JTextField Carnet;
    private javax.swing.JTextField Categoria;
    private javax.swing.JScrollPane ContenedorRazon;
    private javax.swing.JTextField Edicion;
    private javax.swing.JTextField Editorial;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField Idioma;
    private javax.swing.JTextArea RazonEliminar;
    private javax.swing.JTextField Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
